### ISSUE TITLE
Can't pip install in Python 3

### ISSUE THREAD

**Issue by metakermit** [aarongarrett/inspyred#2]
Your README states that you support Python 3+, but I am experiencing errors installing the package.

```
(s3)➜  trunk  pip install inspyred
Downloading/unpacking inspyred
  Downloading inspyred-1.0.tar.gz (80kB): 80kB downloaded
  Running setup.py egg_info for package inspyred
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/kermit/.virtualenvs/s3/build/inspyred/setup.py", line 6, in <module>
        import paver.tasks
      File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
      File "paver-minilib.zip/paver/tasks.py", line 69
        print output
                   ^
    SyntaxError: invalid syntax
```

**Comment by phantomas1234** [comment]
Hi @aarongarrett, I'd love to use inspyred under python 3.4. Any chance you could release a new version?

**Comment by aarongarrett** [comment]
I think so. Let me work on it.

**Comment by ameshkat** [comment]
Hello this is Amir
Unfortunately the previous link to paver-minilib.zip is not valid any more :(
But you could find another version here : https://github.com/paver/paver/blob/master/paver-minilib.zip?raw=true
